### ISSUE TITLE
Hi, A child container failed during start

### ISSUE THREAD

**Issue by zhengfc** [spring-cloud-task-app-starters/jdbchdfs-local#1]
* log
```
Caused by: org.apache.catalina.LifecycleException: A child container failed during start
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
	... 27 common frames omitted
```
I found is because the spring-data-hadoop-store-2.4.0.RELEASE.jar dependency servlet-api-2.5.jar.
So, modify the pom
```
    <dependency>
      <groupId>org.springframework.cloud.task.app</groupId>
      <artifactId>spring-cloud-starter-task-jdbchdfs-local</artifactId>
      <exclusions>
      	<exclusion>
      		<groupId>javax.servlet</groupId>
      		<artifactId>servlet-api</artifactId>
      	</exclusion>
      </exclusions>
    </dependency>
```

**Comment by trisberg** [comment]
This is probably due to some dependency changes after a Spring Boot version upgrade and we should add some excludes to get this to run.

**Comment by sobychacko** [comment]
This exclusion is introduced as of Belmont.M1 release.
